-- MySQL Script generated by MySQL Workbench
-- Wed Feb 23 19:59:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema futbol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema futbol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `futbol` DEFAULT CHARACTER SET utf8mb4 ;
USE `futbol` ;

-- -----------------------------------------------------
-- Table `futbol`.`equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futbol`.`equipos` (
  `codEquipo` INT(11) NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  `liga` INT(11) NOT NULL,
  `localidad` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`codEquipo`),
  INDEX `nombre` (`nombre` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `futbol`.`jugadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futbol`.`jugadores` (
  `numeroID` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `codEquipo` INT(11) NOT NULL,
  PRIMARY KEY (`numeroID`),
  INDEX `codEquipo` (`codEquipo` ASC),
  CONSTRAINT `jugadores_ibfk_1`
    FOREIGN KEY (`codEquipo`)
    REFERENCES `futbol`.`equipos` (`codEquipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
